name: Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Gatsby
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo 'hello'
  deploy:
    needs: build
    steps:
      - name: Echo
        run: echo 'hello'
